loadRacers([
  {"id":1,"img":'<img src="img/table/babd.png">',"name":"Baby Daisy","kart":"Concerto"},
  {"id":2,"img":'<img src="img/table/babl.png">',"name":"Baby Luigi","kart":"Baby Booster"},
  {"id":3,"img":'<img src="img/table/babm.png">',"name":"Baby Mario","kart":"Cheep Charger"},
  {"id":4,"img":'<img src="img/table/babp.png">',"name":"Baby Peach","kart":"Cheep Charger"},
  {"id":5,"img":'<img src="img/table/bir.png">',"name":"Birdo","kart":"Royal Racer"},
  {"id":6,"img":'<img src="img/table/bow.png">',"name":"Bowser","kart":"Flame Flyer"},
  {"id":7,"img":'<img src="img/table/bowj.png">',"name":"Bowser Junior","kart":"Wild Wing"},
  {"id":8,"img":'<img src="img/table/dai.png">',"name":"Daisy","kart":"Standard Kart M"},
  {"id":9,"img":'<img src="img/table/did.png">',"name":"Diddy Kong","kart":"Nostalgia 1"},
  {"id":10,"img":'<img src="img/table/don.png">',"name":"Donkey Kong","kart":"Standard Kart L"},
  {"id":11,"img":'<img src="img/table/dry.png">',"name":"Dry Bowser","kart":"Piranha Prowler"},
  {"id":12,"img":'<img src="img/table/dryb.png">',"name":"Dry Bones","kart":"Standard Kart S"},
  {"id":13,"img":'<img src="img/table/fun.png">',"name":"Funky Kong","kart":"Offroader"},
  {"id":14,"img":'<img src="img/table/kin.png">',"name":"King Boo","kart":"Aero Glider"},
  {"id":15,"img":'<img src="img/table/koo.png">',"name":"Koopa Troopa","kart":"Baby Booster"},
  {"id":16,"img":'<img src="img/table/lui.png">',"name":"Luigi","kart":"Nostalgia"},
  {"id":17,"img":'<img src="img/table/mar.png">',"name":"Mario","kart":"Turbo Blooper"},
  {"id":18,"img":'<img src="img/table/mii.png">',"name":"Carl","kart":"Dragonetti"},
  {"id":19,"img":'<img src="img/table/pea.png">',"name":"Peach","kart":"B Dasher Mk 2"},
  {"id":20,"img":'<img src="img/table/ros.png">',"name":"Rosalina","kart":"Standard Kart L"},
  {"id":21,"img":'<img src="img/table/toa.png">',"name":"Toad","kart":"Rally Romper"},
  {"id":22,"img":'<img src="img/table/toad.png">',"name":"Toadette","kart":"Blue Falcon"},
  {"id":23,"img":'<img src="img/table/wal.png">',"name":"Waluigi","kart":"Piranha Prowler"},
  {"id":24,"img":'<img src="img/table/war.png">',"name":"Wario","kart":"Offroader"},
  {"id":25,"img":'<img src="img/table/yos.png">',"name":"Yoshi","kart":"Royal Racer"}
]);
