loadRacers([
  {"id":1,"table_img":'<img src="img/time-table/babd.png">',"name":"Baby Daisy","kart":"Concerto"},
  {"id":2,"table_img":'<img src="img/time-table/babl.png">',"name":"Baby Luigi","kart":"Baby Booster"},
  {"id":3,"table_img":'<img src="img/time-table/babm.png">',"name":"Baby Mario","kart":"Cheep Charger"},
  {"id":4,"table_img":'<img src="img/time-table/babp.png">',"name":"Baby Peach","kart":"Cheep Charger"},
  {"id":5,"table_img":'<img src="img/time-table/bir.png">',"name":"Birdo","kart":"Royal Racer"},
  {"id":6,"table_img":'<img src="img/time-table/bow.png">',"name":"Bowser","kart":"Flame Flyer"},
  {"id":7,"table_img":'<img src="img/time-table/bowj.png">',"name":"Bowser Junior","kart":"Wild Wing"},
  {"id":8,"table_img":'<img src="img/time-table/dai.png">',"name":"Daisy","kart":"Standard Kart M"},
  {"id":9,"table_img":'<img src="img/time-table/did.png">',"name":"Diddy Kong","kart":"Nostalgia 1"},
  {"id":10,"table_img":'<img src="img/time-table/don.png">',"name":"Donkey Kong","kart":"Standard Kart L"},
  {"id":11,"table_img":'<img src="img/time-table/dry.png">',"name":"Dry Bowser","kart":"Piranha Prowler"},
  {"id":12,"table_img":'<img src="img/time-table/dryb.png">',"name":"Dry Bones","kart":"Standard Kart S"},
  {"id":13,"table_img":'<img src="img/time-table/fun.png">',"name":"Funky Kong","kart":"Offroader"},
  {"id":14,"table_img":'<img src="img/time-table/kin.png">',"name":"King Boo","kart":"Aero Glider"},
  {"id":15,"table_img":'<img src="img/time-table/koo.png">',"name":"Koopa Troopa","kart":"Baby Booster"},
  {"id":16,"table_img":'<img src="img/time-table/lui.png">',"name":"Luigi","kart":"Nostalgia"},
  {"id":17,"table_img":'<img src="img/time-table/mar.png">',"name":"Mario","kart":"Turbo Blooper"},
  {"id":18,"table_img":'<img src="img/time-table/mii.png">',"name":"Carl","kart":"Dragonetti"},
  {"id":19,"table_img":'<img src="img/time-table/pea.png">',"name":"Peach","kart":"B Dasher Mk 2"},
  {"id":20,"table_img":'<img src="img/time-table/ros.png">',"name":"Rosalina","kart":"Standard Kart L"},
  {"id":21,"table_img":'<img src="img/time-table/toa.png">',"name":"Toad","kart":"Rally Romper"},
  {"id":22,"table_img":'<img src="img/time-table/toad.png">',"name":"Toadette","kart":"Blue Falcon"},
  {"id":23,"table_img":'<img src="img/time-table/wal.png">',"name":"Waluigi","kart":"Piranha Prowler"},
  {"id":24,"table_img":'<img src="img/time-table/war.png">',"name":"Wario","kart":"Offroader"},
  {"id":25,"table_img":'<img src="img/time-table/yos.png">',"name":"Yoshi","kart":"Royal Racer"}
]);
