loadRacers([
  {"id":1,"img":"bda","name":"Baby Daisy","kart":"Concerto"},
  {"id":2,"img":"blu","name":"Baby Luigi","kart":"Baby Booster"},
  {"id":3,"img":"bma","name":"Baby Mario","kart":"Cheep Charger"},
  {"id":4,"img":"bpe","name":"Baby Peach","kart":"Cheep Charger"},
  {"id":5,"img":"bir","name":"Birdo","kart":"Royal Racer"},
  {"id":6,"img":"bow","name":"Bowser","kart":"Flame Flyer"},
  {"id":7,"img":"boj","name":"Bowser Junior","kart":"Wild Wing"},
  {"id":8,"img":"dai","name":"Daisy","kart":"Standard Kart M"},
  {"id":9,"img":"did","name":"Diddy Kong","kart":"Nostalgia 1"},
  {"id":10,"img":"don","name":"Donkey Kong","kart":"Standard Kart L"},
  {"id":11,"img":"dry","name":"Dry Bowser","kart":"Piranha Prowler"},
  {"id":12,"img":"drb","name":"Dry Bones","kart":"Standard Kart S"},
  {"id":13,"img":"fun","name":"Funky Kong","kart":"Offroader"},
  {"id":14,"img":"kin","name":"King Boo","kart":"Aero Glider"},
  {"id":15,"img":"koo","name":"Koopa Troopa","kart":"Baby Booster"},
  {"id":16,"img":"lui","name":"Luigi","kart":"Nostalgia"},
  {"id":17,"img":"mar","name":"Mario","kart":"Turbo Blooper"},
  {"id":18,"img":"mii","name":"Carl","kart":"Dragonetti"},
  {"id":19,"img":"pea","name":"Peach","kart":"B Dasher Mk 2"},
  {"id":20,"img":"ros","name":"Rosalina","kart":"Standard Kart L"},
  {"id":21,"img":"toa","name":"Toad","kart":"Rally Romper"},
  {"id":22,"img":"tod","name":"Toadette","kart":"Blue Falcon"},
  {"id":23,"img":"wal","name":"Waluigi","kart":"Piranha Prowler"},
  {"id":24,"img":"war","name":"Wario","kart":"Offroader"},
  {"id":25,"img":"yos","name":"Yoshi","kart":"Royal Racer"}
]);
