loadCircuits([
  {"map":"1. Luigi Circuit", "anim":"luigi-circuit"},
  {"map":"2. Moo Moo Meadows", "anim":"moo-moo-meadows"},
  {"map":"3. Mushroom Gorge", "anim":"mushroom-gorge"},
  {"map":"4. Toad's Factory", "anim":"toads-factory"},
  {"map":"5. Mario Circuit", "anim":"mario-circuit"},
  {"map":"6. Coconut Mall", "anim":"coconut-mall"},
  {"map":"7. DK's Snowboard Cross", "anim":"dks-snowboard-cross"},
  {"map":"8. Wario's Goldmine", "anim":"warios-goldmine"},
  {"map":"9. Daisy Circuit", "anim":"daisy-circuit"},
  {"map":"10. Koopa Cape", "anim":"koopa-cape"},
  {"map":"11. Maple Treeway", "anim":"maple-treeway"},
  {"map":"12. Grumble Volcano", "anim":"grumble-volcano"},
  {"map":"13. Dry Dry Ruins", "anim":"dry-dry-ruins"},
  {"map":"14. Moonview Highway", "anim":"moonview-highway"},
  {"map":"15. Bowser's Castle", "anim":"bowsers-castle"},
  {"map":"16. Rainbow Road", "anim":"rainbow-road"},
  {"map":"17. Peach Beach GCN", "anim":"peach-beach-gcn"},
  {"map":"18. Yoshi Falls DS", "anim":"yoshi-falls-ds"},
  {"map":"19. Ghost Valley 2 SNES", "anim":"ghost-valley-2-snes"},
  {"map":"20. Mario Raceway N64", "anim":"mario-raceway-n64"},
  {"map":"21. Sherbet Land N64", "anim":"sherbet-land-n64"},
  {"map":"22. Shy Guy Beach GBA", "anim":"shy-guy-beach-gba"},
  {"map":"23. Delfino Square DS", "anim":"delfino-square-ds"},
  {"map":"24. Waluigi Stadium GCN", "anim":"waluigi-stadium-gcn"},
  {"map":"25. Dessert Hills DS", "anim":"dessert-hills-ds"},
  {"map":"26. Bowser Castle 3 GBA", "anim":"bowser-castle-3-gba"},
  {"map":"27. DK's Jungle Parkway N64", "anim":"dks-jungle-parkway-n64"},
  {"map":"28. Mario Circuit GCN", "anim":"mario-circuit-gcn"},
  {"map":"29. Mario Circuit 3 SNES", "anim":"mario-circuit-3-snes"},
  {"map":"30. Peach Gardens DS", "anim":"peach-gardens-ds"},
  {"map":"31. DK Mountain GCN", "anim":"dk-mountain-gcn"},
  {"map":"32. Bowser's Castle N64", "anim":"bowsers-castle-n64"}
]);
