loadRacers([
  {"id":1,"img":"bda","name":"Baby Daisy","kart":"Concerto","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":2,"img":"blu","name":"Baby Luigi","kart":"Baby Booster","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":3,"img":"bma","name":"Baby Mario","kart":"Cheep Charger","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":4,"img":"bpe","name":"Baby Peach","kart":"Cheep Charger","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":5,"img":"bir","name":"Birdo","kart":"Royal Racer","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":6,"img":"bow","name":"Bowser","kart":"Flame Flyer","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":7,"img":"boj","name":"Bowser Junior","kart":"Wild Wing","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":8,"img":"dai","name":"Daisy","kart":"Standard Kart M","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":9,"img":"did","name":"Diddy Kong","kart":"Nostalgia 1","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":10,"img":"don","name":"Donkey Kong","kart":"Standard Kart L","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":11,"img":"dry","name":"Dry Bowser","kart":"Piranha Prowler","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":12,"img":"drb","name":"Dry Bones","kart":"Standard Kart S","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":13,"img":"fun","name":"Funky Kong","kart":"Offroader","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":14,"img":"kin","name":"King Boo","kart":"Aero Glider","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":15,"img":"koo","name":"Koopa Troopa","kart":"Baby Booster","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":16,"img":"lui","name":"Luigi","kart":"Nostalgia","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":17,"img":"mar","name":"Mario","kart":"Turbo Blooper","raced":"0","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":18,"img":"mii","name":"Mii","kart":"Dragonetti","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":19,"img":"pea","name":"Peach","kart":"B Dasher Mk 2","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":20,"img":"ros","name":"Rosalina","kart":"Standard Kart L","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":21,"img":"toa","name":"Toad","kart":"Rally Romper","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":22,"img":"tod","name":"Toadette","kart":"Blue Falcon","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":23,"img":"wal","name":"Waluigi","kart":"Piranha Prowler","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":24,"img":"war","name":"Wario","kart":"Offroader","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":25,"img":"yos","name":"Yoshi","kart":"Royal Racer","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"}
]);

loadCircuits([
  {"id":1,"name":"Luigi Circuit","animation":"luigi-circuit"},
  {"id":2,"name":"Moo Moo Meadows","animation":"moo-moo-meadows"},
  {"id":3,"name":"Mushroom Gorge","animation":"mushroom-gorge"},
  {"id":4,"name":"Toad's Factory","animation":"toads-factory"},
  {"id":5,"name":"Mario Circuit","animation":"mario-circuit"},
  {"id":6,"name":"Coconut Mall","animation":"coconut-mall"},
  {"id":7,"name":"DK's Snowboard Cross","animation":"dks-snowboard-cross"},
  {"id":8,"name":"Wario's Goldmine","animation":"warios-goldmine"},
  {"id":9,"name":"Daisy Circuit","animation":"daisy-circuit"},
  {"id":10,"name":"Koopa Cape","animation":"koopa-cape"},
  {"id":11,"name":"Maple Treeway","animation":"maple-treeway"},
  {"id":12,"name":"Grumble Volcano","animation":"grumble-volcano"},
  {"id":13,"name":"Dry Dry Ruins","animation":"dry-dry-ruins"},
  {"id":14,"name":"Moonview Highway","animation":"moonview-highway"},
  {"id":15,"name":"Bowser's Castle","animation":"bowsers-castle"},
  {"id":16,"name":"Rainbow Road","animation":"rainbow-road"},
  {"id":17,"name":"Peach Beach GCN","animation":"peach-beach-gcn"},
  {"id":18,"name":"Yoshi Falls DS","animation":"yoshi-falls-ds"},
  {"id":19,"name":"Ghost Valley 2 SNES","animation":"ghost-valley-2-snes"},
  {"id":20,"name":"Mario Raceway N64","animation":"mario-raceway-n64"},
  {"id":21,"name":"Sherbet Land N64","animation":"sherbet-land-n64"},
  {"id":22,"name":"Shy Guy Beach GBA","animation":"shy-guy-beach-gba"},
  {"id":23,"name":"Delfino Square DS","animation":"delfino-square-ds"},
  {"id":24,"name":"Waluigi Stadium GCN","animation":"waluigi-stadium-gcn"},
  {"id":25,"name":"Desert Hills DS","animation":"desert-hills-ds"},
  {"id":26,"name":"Bowser Castle 3 GBA","animation":"bowser-castle-3-gba"},
  {"id":27,"name":"DK's Jungle Parkway N64","animation":"dks-jungle-parkway-n64"},
  {"id":28,"name":"Mario Circuit GCN","animation":"mario-circuit-gcn"},
  {"id":29,"name":"Mario Circuit 3 SNES","animation":"mario-circuit-3-snes"},
  {"id":30,"name":"Peach Gardens DS","animation":"peach-gardens-ds"},
  {"id":31,"name":"DK Mountain GCN","animation":"dk-mountain-gcn"},
  {"id":32,"name":"Bowser's Castle N64","animation":"bowsers-castle-n64"}
]);
