loadRacers([
  {"id":1,"img":"bda","name":"Baby Daisy","kart":"Concerto","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":2,"img":"blu","name":"Baby Luigi","kart":"Baby Booster","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":3,"img":"bma","name":"Baby Mario","kart":"Cheep Charger","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":4,"img":"bpe","name":"Baby Peach","kart":"Cheep Charger","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":5,"img":"bir","name":"Birdo","kart":"Royal Racer","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":6,"img":"bow","name":"Bowser","kart":"Flame Flyer","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":7,"img":"boj","name":"Bowser Junior","kart":"Wild Wing","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":8,"img":"dai","name":"Daisy","kart":"Standard Kart M","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":9,"img":"did","name":"Diddy Kong","kart":"Nostalgia 1","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":10,"img":"don","name":"Donkey Kong","kart":"Standard Kart L","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":11,"img":"dry","name":"Dry Bowser","kart":"Piranha Prowler","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":12,"img":"drb","name":"Dry Bones","kart":"Standard Kart S","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":13,"img":"fun","name":"Funky Kong","kart":"Offroader","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":14,"img":"kin","name":"King Boo","kart":"Aero Glider","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":15,"img":"koo","name":"Koopa Troopa","kart":"Baby Booster","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":16,"img":"lui","name":"Luigi","kart":"Nostalgia","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":17,"img":"mar","name":"Mario","kart":"Turbo Blooper","raced":"0","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":18,"img":"mii","name":"Carl","kart":"Dragonetti","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":19,"img":"pea","name":"Peach","kart":"B Dasher Mk 2","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":20,"img":"ros","name":"Rosalina","kart":"Standard Kart L","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":21,"img":"toa","name":"Toad","kart":"Rally Romper","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":22,"img":"tod","name":"Toadette","kart":"Blue Falcon","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":23,"img":"wal","name":"Waluigi","kart":"Piranha Prowler","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":24,"img":"war","name":"Wario","kart":"Offroader","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"},
  {"id":25,"img":"yos","name":"Yoshi","kart":"Royal Racer","raced":"0","hrs":"0","min":"0","sec":"0","mil":"0"}
]);

loadCircuits([
  {"track":"1. Luigi Circuit","animation":"luigi-circuit"},
  {"track":"2. Moo Moo Meadows","animation":"moo-moo-meadows"},
  {"track":"3. Mushroom Gorge","animation":"mushroom-gorge"},
  {"track":"4. Toad's Factory","animation":"toads-factory"},
  {"track":"5. Mario Circuit","animation":"mario-circuit"},
  {"track":"6. Coconut Mall","animation":"coconut-mall"},
  {"track":"7. DK's Snowboard Cross","animation":"dks-snowboard-cross"},
  {"track":"8. Wario's Goldmine","animation":"warios-goldmine"},
  {"track":"9. Daisy Circuit","animation":"daisy-circuit"},
  {"track":"10. Koopa Cape","animation":"koopa-cape"},
  {"track":"11. Maple Treeway","animation":"maple-treeway"},
  {"track":"12. Grumble Volcano","animation":"grumble-volcano"},
  {"track":"13. Dry Dry Ruins","animation":"dry-dry-ruins"},
  {"track":"14. Moonview Highway","animation":"moonview-highway"},
  {"track":"15. Bowser's Castle","animation":"bowsers-castle"},
  {"track":"16. Rainbow Road","animation":"rainbow-road"},
  {"track":"17. Peach Beach GCN","animation":"peach-beach-gcn"},
  {"track":"18. Yoshi Falls DS","animation":"yoshi-falls-ds"},
  {"track":"19. Ghost Valley 2 SNES","animation":"ghost-valley-2-snes"},
  {"track":"20. Mario Raceway N64","animation":"mario-raceway-n64"},
  {"track":"21. Sherbet Land N64","animation":"sherbet-land-n64"},
  {"track":"22. Shy Guy Beach GBA","animation":"shy-guy-beach-gba"},
  {"track":"23. Delfino Square DS","animation":"delfino-square-ds"},
  {"track":"24. Waluigi Stadium GCN","animation":"waluigi-stadium-gcn"},
  {"track":"25. Desert Hills DS","animation":"desert-hills-ds"},
  {"track":"26. Bowser Castle 3 GBA","animation":"bowser-castle-3-gba"},
  {"track":"27. DK's Jungle Parkway N64","animation":"dks-jungle-parkway-n64"},
  {"track":"28. Mario Circuit GCN","animation":"mario-circuit-gcn"},
  {"track":"29. Mario Circuit 3 SNES","animation":"mario-circuit-3-snes"},
  {"track":"30. Peach Gardens DS","animation":"peach-gardens-ds"},
  {"track":"31. DK Mountain GCN","animation":"dk-mountain-gcn"},
  {"track":"32. Bowser's Castle N64","animation":"bowsers-castle-n64"}
]);
