loadRacers([
  {"id":1,"img":"bda","name":"Baby Daisy","kart":"Concerto","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":2,"img":"blu","name":"Baby Luigi","kart":"Baby Booster","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":3,"img":"bma","name":"Baby Mario","kart":"Cheep Charger","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":4,"img":"bpe","name":"Baby Peach","kart":"Cheep Charger","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":5,"img":"bir","name":"Birdo","kart":"Royal Racer","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":6,"img":"bow","name":"Bowser","kart":"Flame Flyer","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":7,"img":"boj","name":"Bowser Junior","kart":"Wild Wing","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":8,"img":"dai","name":"Daisy","kart":"Standard Kart M","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":9,"img":"did","name":"Diddy Kong","kart":"Nostalgia 1","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":10,"img":"don","name":"Donkey Kong","kart":"Standard Kart L","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":11,"img":"dry","name":"Dry Bowser","kart":"Piranha Prowler","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":12,"img":"drb","name":"Dry Bones","kart":"Standard Kart S","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":13,"img":"fun","name":"Funky Kong","kart":"Offroader","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":14,"img":"kin","name":"King Boo","kart":"Aero Glider","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":15,"img":"koo","name":"Koopa Troopa","kart":"Baby Booster","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":16,"img":"lui","name":"Luigi","kart":"Nostalgia","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":17,"img":"mar","name":"Mario","kart":"Turbo Blooper","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":18,"img":"mii","name":"Carl","kart":"Dragonetti","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":19,"img":"pea","name":"Peach","kart":"B Dasher Mk 2","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":20,"img":"ros","name":"Rosalina","kart":"Standard Kart L","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":21,"img":"toa","name":"Toad","kart":"Rally Romper","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":22,"img":"tod","name":"Toadette","kart":"Blue Falcon","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":23,"img":"wal","name":"Waluigi","kart":"Piranha Prowler","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":24,"img":"war","name":"Wario","kart":"Offroader","hrs":"0","min":"00","sec":"00","mil":"000"},
  {"id":25,"img":"yos","name":"Yoshi","kart":"Royal Racer","hrs":"0","min":"00","sec":"00","mil":"000"}
]);
